parameters:
#    divona_standings.example.class: Divona\StandingsBundle\Example

services:
#    divona_standings.example:
#        class: %divona_standings.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
