DivonaUserBundle:
    resource: "@DivonaUserBundle/Resources/config/routing.yml"
    prefix:   /

DivonaStandingsBundle:
    resource: "@DivonaStandingsBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
