parameters:
#    divona_user.example.class: Divona\UserBundle\Example

services:
#    divona_user.example:
#        class: %divona_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
